INSERT INTO CATEGORIA_EMPRESA (CATEGORIA_NOME)  VALUES ( 'Tecnologia da Informação' ), ( 'Ciência de Dados' );
INSERT INTO categoria_problema (CATEGORIA_NOME)  VALUES ( 'UI' ), ( 'Segurança' ), ('UX');

INSERT INTO EMPRESA (EMPRESA_NOME, CATEGORIA_EMPRESA_ID) VALUES ('INNOVA', 1);

INSERT INTO FUNCAO (FUNCAO_NOME, PRIVILEGIOS_DE_ACESSO, EMPRESA_ID) VALUES ('Administrador', 'ADMINISTRADOR', 1);

INSERT INTO FUNCIONARIO (ATIVO, DATA_CRIACAO, FUNCIONARIO_EMAIL, FUNCIONARIO_NOME, FUNCIONARIO_SOBRENOME, SENHA, EMPRESA_ID, FUNCAO_ID)
VALUES ( TRUE, CURRENT_DATE, 'rodrigocury@ufu.br', 'Rodrigo', 'Cury', '$2a$10$6ilMKy6bUP6tL7.I451cPOAuhEqMsyGzzSWLTZZQMWa4ljcHlzpZi',1 ,1);