INSERT INTO CATEGORIA_EMPRESA (CATEGORIA_NOME)  VALUES ( 'Tecnologia da Informação' ), ( 'Ciência de Dados' );
INSERT INTO CATEGORIA_PROBLEMA (CATEGORIA_NOME)  VALUES ( 'UI' ), ( 'Segurança' ), ('UX');

INSERT INTO EMPRESA (EMPRESA_NOME, CATEGORIA_EMPRESA_ID) VALUES ('INNOVA', 1);

INSERT INTO TIME (TIME_NOME, EMPRESA_EMPRESA_ID) VALUES ('Time 1', 1);

INSERT INTO FUNCAO (FUNCAO_NOME, PRIVILEGIOS_DE_ACESSO, EMPRESA_ID)
VALUES ('Administrador', 'ADMINISTRADOR', 1),
       ('Gerente', 'GERENTE', 1),
       ('Funcionario', 'FUNCIONARIO', 1);

INSERT INTO FUNCIONARIO (ATIVO, DATA_CRIACAO, FUNCIONARIO_EMAIL, FUNCIONARIO_NOME, FUNCIONARIO_SOBRENOME, SENHA, EMPRESA_ID, FUNCAO_ID, TIME_ID) VALUES
( TRUE, CURRENT_DATE, 'rodrigocury@ufu.br', 'Rodrigo', 'Cury', '$2a$10$6ilMKy6bUP6tL7.I451cPOAuhEqMsyGzzSWLTZZQMWa4ljcHlzpZi',1 ,1, 1),
( TRUE, CURRENT_DATE, 'luigi@ufu.br', 'Luigi', 'Souza', '$2a$10$6ilMKy6bUP6tL7.I451cPOAuhEqMsyGzzSWLTZZQMWa4ljcHlzpZi',1 ,2, 1),
( TRUE, CURRENT_DATE, 'roger@ufu.br', 'Roger', 'Souza', '$2a$10$6ilMKy6bUP6tL7.I451cPOAuhEqMsyGzzSWLTZZQMWa4ljcHlzpZi',1 ,3, 1);

INSERT INTO PROJETO (PROJETO_NOME, EMPRESA_ID, FUNCIONARIO_RESPONSAVEL_FUNCIONARIO_ID) VALUES
('PROJETO 1',1,  1),
('PROJETO 2', 1, 2);

INSERT INTO TIME_PROJETO (TIME_ID, PROJETO_ID) values
(1,1),
(1,2);